### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by mage1k99**
changed to `implementation`

### CODE REVIEW

**Comment by mage1k99** [comment]
Will add Kotlin documentation soon.

**Comment by anidotnet** [comment]
Thanks for the PR. Which kotlin document are you referring to?

**Comment by mage1k99** [comment]
> Thanks for the PR. Which kotlin document are you referring to?

Was saying that will update it for Potassium Nitrite too 😅

**Comment by anidotnet** [comment]
OK. Merged it.

**Pull request merged**
